language: julia
julia:
    - 1.3
    - nightly
os:
    - linux

codecov: true
coveralls: true

after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

matrix:
    allow_failures:
        - julia: nightly

notifications:
    email: false
